name: happyshop
description: Ecommerce App

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  cached_network_svg_image: ^1.1.0
  change_app_package_name: ^1.4.0
  cloud_firestore: ^5.5.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dropdown_search: ^6.0.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_crashlytics: ^4.2.0
  firebase_messaging: ^15.1.6
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_map: ^7.0.2
  flutter_native_splash: ^2.4.3
  flutter_otp_text_field: ^1.2.0
  flutter_paypal_checkout: ^1.0.1
  flutter_ringtone_player: ^4.0.0
  flutter_screenutil: ^5.9.3
  flutter_stripe: ^11.3.0
  flutter_svg: ^2.0.16
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  google_polyline_algorithm: ^3.1.0
  icons_launcher: ^3.0.0
  jiffy: ^6.3.2
  latlong2: ^0.9.1
  lottie: ^3.3.0
  otp_text_field: ^1.1.3
  path: ^1.9.0
  pay: ^2.0.0
  rating_dialog: ^2.0.4
  responsive_builder: ^0.7.1
  routing_client_dart: ^0.5.5
  # sentry_flutter: ^7.9.0
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dependency_overrides:
  http: ^1.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
# flutter pub run change_app_package_name:main com.amadytech.happyshop
# flutter pub get
# dart run icons_launcher:create
icons_launcher:
  image_path: "assets/images/logoapp.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
    macos:
      enable: false
    windows:
      enable: false
    linux:
      enable: false

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/ic_launcher.png"
  background_image: "assets/images/background_ic_launcher.png"
  branding: "assets/images/background_ic_launcher.png"
  # color_dark: "#121212"
  color_dark: "#ffffff"
  image_dark: "assets/images/ic_launcher.png"
  branding_dark: "assets/images/background_ic_launcher.png"
  android_12:
    image: "assets/images/ic_launcher.png"
    icon_background_color: "#ffffff"
    image_dark: "assets/images/ic_launcher.png"
    icon_background_color_dark: "#ffffff"
  android_gravity: center
  web_image_mode: center
  ios_content_mode: center
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/lottie/
    - assets/svg/
    - assets/icons/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700
