// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLvVC62jM_11orlcQDNzGCikQ93hyXRWY',
    appId: '1:102571397024:web:0aa3b2df7f1d0466561ec5',
    messagingSenderId: '102571397024',
    projectId: 'happayshop-98725',
    authDomain: 'happayshop-98725.firebaseapp.com',
    storageBucket: 'happayshop-98725.appspot.com',
    measurementId: 'G-0FQ2PKJ5B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUkc0-suSrM88qK1UMnAkTCcBXz0mlm0k',
    appId: '1:102571397024:android:286695232081bbb0561ec5',
    messagingSenderId: '102571397024',
    projectId: 'happayshop-98725',
    storageBucket: 'happayshop-98725.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Pgo9xSedZUwyj8jRCdTG6Nl_NFsHXaU',
    appId: '1:102571397024:ios:1b760fdde9df7fce561ec5',
    messagingSenderId: '102571397024',
    projectId: 'happayshop-98725',
    storageBucket: 'happayshop-98725.appspot.com',
    androidClientId: '102571397024-0ef9q5263stihcc20f11sgvv277ogv42.apps.googleusercontent.com',
    iosClientId: '102571397024-2e20mc2ccq97b3vp541bed8evm9lq8l3.apps.googleusercontent.com',
    iosBundleId: 'com.amadytech.happyshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Pgo9xSedZUwyj8jRCdTG6Nl_NFsHXaU',
    appId: '1:102571397024:ios:3e0a4868734d4a04561ec5',
    messagingSenderId: '102571397024',
    projectId: 'happayshop-98725',
    storageBucket: 'happayshop-98725.appspot.com',
    androidClientId: '102571397024-0ef9q5263stihcc20f11sgvv277ogv42.apps.googleusercontent.com',
    iosClientId: '102571397024-g53ftba9pl119qi22g7ejnd229ec9nlu.apps.googleusercontent.com',
    iosBundleId: 'com.amadytech.happyshop.RunnerTests',
  );
}
